-- Initialize coil materials
INSERT INTO materials (name, type, thickness, color, quantity, unit) VALUES
('Coil', 'coil', 0.60, 'coffee_brown', 0, 'sqft'),
('Coil', 'coil', 0.60, 'black_shine', 0, 'sqft'),
('Coil', 'coil', 0.60, 'blue_color', 0, 'sqft'),
('Coil', 'coil', 0.60, 'butter_milk', 0, 'sqft'),
('Coil', 'coil', 0.60, 'chocolate_brown', 0, 'sqft'),
('Coil', 'coil', 0.60, 'black_mate', 0, 'sqft'),
('Coil', 'coil', 0.60, 'beige', 0, 'sqft'),
('Coil', 'coil', 0.47, 'coffee_brown', 0, 'sqft'),
('Coil', 'coil', 0.47, 'black_shine', 0, 'sqft'),
('Coil', 'coil', 0.47, 'blue_color', 0, 'sqft'),
('Coil', 'coil', 0.47, 'butter_milk', 0, 'sqft'),
('Coil', 'coil', 0.47, 'chocolate_brown', 0, 'sqft'),
('Coil', 'coil', 0.47, 'black_mate', 0, 'sqft'),
('Coil', 'coil', 0.47, 'beige', 0, 'sqft');

-- Initialize other materials
INSERT INTO materials (name, type, quantity, unit) VALUES
('Motor', 'other', 0, 'pieces'),
('GI bar', 'other', 0, 'pieces'),
('Puli', 'other', 0, 'pieces'),
('Spring', 'other', 0, 'pieces'),
('Bolt nails', 'other', 0, 'pieces'),
('Washer', 'other', 0, 'pieces'),
('L angal', 'other', 0, 'pieces'),
('U bolt', 'other', 0, 'pieces'),
('Ancor bolt', 'other', 0, 'pieces'),
('U channel coil', 'other', 0, 'pieces'),
('Sqew nails', 'other', 0, 'pieces'),
('Nilon strips', 'other', 0, 'meters'),
('Stepler rails', 'other', 0, 'pieces'),
('Tomb bar', 'other', 0, 'pieces'),
('Cutting wheel', 'other', 0, 'pieces'),
('Paint', 'other', 0, 'liters'),
('Tiner', 'other', 0, 'liters'),
('Center lock', 'other', 0, 'pieces'),
('Down lock', 'other', 0, 'pieces'),
('Side lock', 'other', 0, 'pieces'),
('Door hooks', 'other', 0, 'pieces'),
('Covering coils', 'other', 0, 'sqft'),
('Box bar 1x1.2mm', 'other', 0, 'pieces'),
('Box bar 1x1/2mm', 'other', 0, 'pieces'),
('Revert 5/32 x 1/2', 'other', 0, 'pieces'),
('Revert 5/32 x 1', 'other', 0, 'pieces'),
('Unit box', 'other', 0, 'pieces'),
('Flat iron 1"x 6mm', 'other', 0, 'pieces'),
('Flat iron 1" x 1/2 x 6mm', 'other', 0, 'pieces'),
('Roll plug 6mm', 'other', 0, 'pieces'),
('Roll plug nut', 'other', 0, 'pieces'),
('Case', 'other', 0, 'pieces'),
('Steel bar', 'other', 0, 'pieces'),
('Eye hole', 'other', 0, 'pieces'),
('Letter box', 'other', 0, 'pieces'),
('Letter holder', 'other', 0, 'pieces'),
('Tomb bar beedin', 'other', 0, 'pieces'),
('Gate bush', 'other', 0, 'pieces'),
('Saraneru', 'other', 0, 'pieces'),
('Kondipattam', 'other', 0, 'pieces'),
('12 welding sticks', 'other', 0, 'pieces'),
('13A plug top', 'other', 0, 'pieces'),
('Door handle', 'other', 0, 'pieces'),
('Stop bracket', 'other', 0, 'pieces'),
('Stop bracket nails', 'other', 0, 'pieces'),
('Dagara kambi 10mm', 'other', 0, 'pieces'),
('Control unit + remote', 'other', 0, 'pieces');

-- Create default admin user
INSERT INTO users (username, password, role, name, contact) VALUES
('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin', 'System Admin', '0000000000');
-- Password is "password"
